In [1]:
import torch

In [3]:
x = torch.empty(5, 3)
print(x)

tensor([[1.8547e-28, 4.5637e-41, 1.8547e-28],
        [4.5637e-41, 3.0308e+24, 6.1207e-04],
        [4.8419e+30, 1.7256e+25, 3.1766e+30],
        [1.7035e+25, 1.9346e-19, 1.2414e+28],
        [1.1728e-19, 4.9556e+28, 8.9070e-15]])


In [4]:
x = torch.rand(5, 3)
print(x)

tensor([[0.4883, 0.9921, 0.4586],
        [0.3118, 0.3338, 0.0612],
        [0.7979, 0.7693, 0.7336],
        [0.5210, 0.1664, 0.1790],
        [0.2763, 0.0338, 0.3470]])


In [5]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [6]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [7]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.3725, -0.7642, -1.7025],
        [ 1.3148, -0.2385, -0.7873],
        [ 0.3818, -1.8284,  0.2405],
        [ 1.3337, -0.8319,  0.4103],
        [-0.2118,  0.1624, -1.1263]])


In [8]:
print(x.size())

torch.Size([5, 3])


In [10]:
y = torch.rand(5, 3)
print(x + y)

tensor([[-0.2119, -0.1541, -0.7979],
        [ 2.0925,  0.1070,  0.1145],
        [ 0.6047, -1.2025,  0.6513],
        [ 2.2786, -0.1436,  1.3418],
        [ 0.6399,  0.6041, -0.4781]])


In [3]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [12]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [13]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [14]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [15]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [4]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))

tensor([[-0.5464,  1.0094,  1.7745,  0.0666],
        [ 0.1804,  2.0186,  0.5165,  1.1967],
        [ 0.1221,  0.0605,  0.7138,  1.9053],
        [ 0.1825,  1.9890,  0.4567, -0.3853]], device='cuda:0')
tensor([[-0.5464,  1.0094,  1.7745,  0.0666],
        [ 0.1804,  2.0186,  0.5165,  1.1967],
        [ 0.1221,  0.0605,  0.7138,  1.9053],
        [ 0.1825,  1.9890,  0.4567, -0.3853]], dtype=torch.float64)
